### ISSUE TITLE
jieba--current-dir在spacemacs中返回错误的值

### ISSUE THREAD

**Issue by ruibinx** [cireu/jieba.el#4]
在Spacemacs中 `(load-in-progress load-file-name)`会返回`~/.emacs.d/init.el`，而不是jieba.el所在的目录。

我的Spacemacs配置如下，
```elisp
(defconst ruibin-packages
  '(
    (jieba :location local)
    jsonrpc
    )
)
(defun ruibin/init-jsonrpc ()
  (require 'jsonrpc)
)

(defun ruibin/init-jieba ()
  (require 'jieba)
  (jieba-mode)
  )
```
启动时会找不到simple-jieba-server.js。

```
module.js:550
    throw err;
    ^

Error: Cannot find module '/Users/ruibin/.emacs.d/simple-jieba-server.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Process JIEBA-SERVER stderr finished
```
对Elisp不是很熟悉，搜索了一下没找到更好的定位当前文件的方式，这个问题是不是无解的？

**Comment by cireu** [comment]
你可以设置`jieba-server-start-args`为`'("node" "/path/to/simple-jieba-server.js")`

感谢反馈，我会找下看看有没有更好的方式来获取路径

**Comment by ruibinx** [comment]
谢谢，这样是可以的。

**Comment by cireu** [comment]
请测试 #5

**Comment by ruibinx** [comment]
一切正常了，受教，感谢!

**Comment by cireu** [comment]
合并到主分支了，have fun
